# .github/workflows/deploy.yml

name: Deploy Astro site to Pages

on:
  # Runs on pushes targeting the default branch (usually main or master)
  push:
    branches: [$default-branch] # Replace $default-branch with your main branch name, e.g., main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4 # Uses version 4 of the checkout action

      - name: Setup Node.js environment
        uses: actions/setup-node@v4 # Uses version 4 of the setup-node action
        with:
          node-version: "20" # Specify your Node.js version (Astro requires >= 18.14.1)
          cache: 'npm' # Automatically caches npm dependencies

      - name: Install dependencies
        run: npm ci # Use 'ci' for faster, more reliable installs in CI environments

      - name: Build Astro site
        run: npm run build # Runs the build script defined in your package.json

      # This step is crucial for GitHub Pages deployment
      - name: Upload artifact for GitHub Pages deployment
        uses: actions/upload-pages-artifact@v3 # Uses version 3 of the upload-pages-artifact action
        with:
          # Astro builds to 'dist' by default. Change this if your `astro.config.mjs` specifies a different `outDir`.
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Sets the deployment environment URL in GitHub
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Uses version 4 of the deploy-pages action